services:
  mongo:
    image: mongo:latest
    container_name: mongo-std-1
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    ports:
      - 127.0.0.1:27717:27017
    restart: unless-stopped
    volumes:
      - /helium-etl/hip94-run/mongo_data:/data/db
      - /helium-etl/hip94-run/mongo_dump:/dump
    networks:
      - public_net
      - hip94_net

  hip94:
    image: disk91/hip94
    container_name: hip94
    restart: unless-stopped
    volumes:
      - /helium-etl/hip94-run/cache-files:/files
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - AWS_ACCESS_KEY=
      - AWS_SECRET_KEY=
      - MONGO_COLLECTION=helium-hip94-cfe
      - ETL_SERVER=https://foo.bar
    mem_limit: 8000m
    logging: &logs
      driver: "json-file"
      options:
        max-size: "100m"
    networks:
      - public_net
      - hip94_net

networks:
  public_net:
  hip94_net:
    internal: true